#!/bin/bash

BOARD=$(cat /boot/boot/batocera.board)
# We only want the script to run for these devices
if [ "$BOARD" != "trimui-brick" ] && [ "$BOARD" != "trimui-smart-pro" ]; then
    exit 1
fi

case "${1}" in
   suspend)
      # Disable xradio Wi-Fi drivers
      if [ "$BOARD" = "trimui-smart-pro" ]; then
        rmmod xradio_wlan_tsp
      else
        rmmod xradio_wlan
      fi
      ;;
   thaw|resume)
      # Re-enable xradio Wi-Fi drivers
      if [ "$BOARD" = "trimui-smart-pro" ]; then
        insmod /lib/modules/4.9.191/xradio_wlan.ko
      else
        insmod /lib/modules/4.9.191/xradio_wlan_tsp.ko
      fi
      
      # Make sure Wi-Fi isn't soft-blocked
      rfkill unblock wifi
      ;;
esac
exit 0
