[general]
skip_boot_anim = true
show_welcome = false
screenshot_dir = '/storage/roms/screenshots'

[input.bindings]
port1 = '0000f353526574726f696420506f6300'

[display]
renderer = 'VULKAN'

[display.quality]
surface_scale = 1

[display.window]
fullscreen_on_startup = true
vsync = true

[display.ui]
show_menubar = false
fit = 'stretch'
aspect_ratio = 'native'

[sys]
mem_limit = '128'

[sys.files]
bootrom_path = '/storage/roms/bios/xemu/bios/mcpx_1.0.bin'
flashrom_path = '/storage/roms/bios/xemu/bios/Complex_4627v1.03.bin'
eeprom_path = '/storage/roms/bios/xemu/eeprom/eeprom.bin'
hdd_path = '/storage/roms/bios/xemu/hdd/xbox_hdd.qcow2'

[perf]
cache_shaders = false
override_clockspeed = false
cpu_clockspeed_scale = 1.000000
